version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: crypto-exchange-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: crypto-exchange-redis
    restart: always
    ports:
      - '${NONCE_REDIS_PORT}:6379'

volumes:
  postgres_data:
